task:
  name: stable-x86_64-unknown-freebsd
  freebsd_instance:
    matrix:
      - image: freebsd-12-0-release-amd64
      - image: freebsd-11-2-release-amd64
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - pkg install -y curl git
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  submodule_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  check_script:
    - . $HOME/.cargo/env
    - cargo check --all-targets
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all-targets --verbose
  test_script:
    - . $HOME/.cargo/env
    # Currently must run tests with `--test-threads=1` because we're testing
    # the contents of log messages in our tests and the current logging
    # infrastructure does not support that well for multithreaded code.
    # See comment at top of `tests/common/test_logger.rs` for more detail.
    # We plan to switch out our logging infrastructure for a solution that
    # is more robust to multithreaded code in the future. See issue #TBD.
    - cargo test --no-fail-fast --verbose --all -- --test-threads=1 --nocapture
