stages:
 - template: azure/stages.yml@templates
   parameters:
#    codecov_token: $(CODECOV_TOKEN_SECRET)
     single_threaded: true
#    nightly_coverage: false
     minrust: 1.36.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: jonhoo
