[package]
name = "inferno"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
regex = "1.0"
structopt = "0.2"
lazy_static = "1.2"

[[bin]]
name = "inferno-collapse-perf"
path = "src/collapse-perf.rs"
