[package]
name = "inferno"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"

[profile.release]
debug = true

[[bin]]
name = "inferno-collapse-perf"
path = "src/collapse-perf.rs"
